CREATE DATABASE PROJETO_FERIADOS;

USE PROJETO_FERIADOS;


DROP DATABASE PROJETO_FERIADOS;

CREATE TABLE TBL_FERIADO(
ID_FERIADO BIGINT IDENTITY PRIMARY KEY,
TIPO_FERIADO VARCHAR(20) NOT NULL, 
DS_FERIADO VARCHAR(50) NOT NULL,
DT_FERIADO DATE NOT NULL 
);




INSERT INTO TBL_FERIADO(TIPO_FERIADO, DS_FERIADO, DT_FERIADO) 
VALUES('Nacional','Confraternização Universal','2019/01/01');




INSERT INTO TBL_FERIADO(TIPO_FERIADO, DS_FERIADO, DT_FERIADO) VALUES
('Nacinonal','Independência do Brasil','2019/09/07');


INSERT INTO TBL_FERIADO(TIPO_FERIADO, DS_FERIADO, DT_FERIADO) VALUES
('Municipal','Aniversário da cidade São Paulo','2019/01/25');



INSERT INTO TBL_FERIADO(TIPO_FERIADO, DS_FERIADO, DT_FERIADO) VALUES
('Municipal','Sexta-Feira santa','2019/04/19');

INSERT INTO TBL_FERIADO(TIPO_FERIADO, DS_FERIADO, DT_FERIADO) VALUES
('Estadual','Revolução Constitucionalista','2019/09/07');



SELECT * FROM TBL_FERIADO;



--INSERT INTO TBL_PERSONAGEM (TX_NOME, TX_APELIDO, TP_ESPECIE, TP_SEXO, ST_PERSONAGEM) VALUES
--('Número 17',NULL,'ANDROIDE','M','VIVO');
--INSERT INTO TBL_PERSONAGEM (TX_NOME, TX_APELIDO, TP_ESPECIE, TP_SEXO, ST_PERSONAGEM) VALUES
--('Número 18',NULL,'ANDROIDE','F','VIVO');
--SELECT * FROM TBL_PERSONAGEM;--
